# Generated by Django 6.0.5 on 2026-08-04 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS_Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200, verbose_name='نام')),
                ('l_name', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('phone', models.BigIntegerField(unique=True, verbose_name='شماره تماس')),
            ],
        ),
        migrations.CreateModel(
            name='SMS_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_panel', models.CharField(choices=[('SMS.IR', 'SMS.IR')], max_length=10)),
                ('user_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام کاربری')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='رمز عبور')),
                ('api_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='کلید API')),
                ('line_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره خط ارسال')),
            ],
            options={
                'verbose_name': 'سرویس پیامک',
                'verbose_name_plural': 'سرویس\u200cهای پیامک',
            },
        ),
        migrations.CreateModel(
            name='SMS_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('signup', 'ثبت نام'), ('login', 'ورود'), ('personel_night_order', 'سفارش به نام پرسنل'), ('Buy Notification', 'ارسال خرید')], max_length=100, verbose_name='نوع قالب پیامک')),
                ('template_id', models.CharField(max_length=200, verbose_name='شناسه قالب')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='otp_manager.sms_service', verbose_name='سرویس پیامک')),
            ],
            options={
                'verbose_name': 'قالب پیامک',
                'verbose_name_plural': 'قالب\u200cهای پیامک',
            },
        ),
        migrations.CreateModel(
            name='SMS_Recievers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_person', to='otp_manager.sms_persons', verbose_name='دریافت کننده')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_template', to='otp_manager.sms_template', verbose_name='قالب پیامک')),
            ],
        ),
    ]
