# Generated by Django 6.0.7 on 2026-08-01 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True, verbose_name='کد ماده')),
                ('item_name', models.CharField(max_length=200, verbose_name='نام ماده')),
                ('adjustment_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تنظیم')),
                ('send_sms', models.BooleanField(default=True, verbose_name='ارسال پیامک')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'تنظیم مواد',
                'verbose_name_plural': 'تنظیمات مواد',
                'ordering': ['item_code'],
            },
        ),
    ]
