# Generated by Django 6.0.7 on 2026-08-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان اجرا')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('running', 'در حال اجرا'), ('success', 'موفق'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('message', models.TextField(blank=True, verbose_name='پیام')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='نتیجه')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='مدت زمان اجرا (ثانیه)')),
            ],
            options={
                'verbose_name': 'لاگ وظیفه روزانه',
                'verbose_name_plural': 'لاگ\u200cهای وظایف روزانه',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAdjustmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, verbose_name='کد ماده')),
                ('item_name', models.CharField(max_length=200, verbose_name='نام ماده')),
                ('adjustment_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد تنظیم')),
                ('old_quantity', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='موجودی قبلی')),
                ('new_quantity', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='موجودی جدید')),
                ('send_sms', models.BooleanField(default=False, verbose_name='ارسال پیامک')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان پردازش')),
            ],
            options={
                'verbose_name': 'تاریخچه تنظیمات',
                'verbose_name_plural': 'تاریخچه تنظیمات مواد',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.AlterField(
            model_name='materialadjustment',
            name='send_sms',
            field=models.BooleanField(default=False, verbose_name='ارسال پیامک'),
        ),
    ]
