# Generated by Django 6.0.5 on 2026-07-02 10:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='سیستم مدیریت دیتاست', max_length=255, verbose_name='نام اپلیکیشن')),
                ('name_en', models.CharField(default='Dataset Management System', max_length=255, verbose_name='نام اپلیکیشن (انگلیسی)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='assets/logo/', verbose_name='لوگوی اپلیکیشن')),
                ('sidebar_logo', models.ImageField(blank=True, null=True, upload_to='assets/sidebar_logo/', verbose_name='لوگوی سایدبار')),
                ('sidebar_title', models.CharField(default='test', max_length=255)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='assets/favicon/', verbose_name='فاویکون')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات اپلیکیشن')),
                ('base_dataset_dir', models.CharField(blank=True, default='datasets', max_length=1000, verbose_name='محل ذخیره سازی دیتاست ها')),
                ('base_ai_models_dir', models.CharField(blank=True, default='ai_models', max_length=1000, verbose_name='محل ذخیره سازی مدل ها')),
                ('max_datasets', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='حداکثر تعداد دیتاست')),
                ('max_users', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='حداکثر تعداد کاربران')),
                ('max_classes_per_dataset', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='حداکثر تعداد کلاس در هر دیتاست')),
                ('max_images_per_dataset', models.IntegerField(default=10000, validators=[django.core.validators.MinValueValidator(1)], verbose_name='حداکثر تعداد تصویر در هر دیتاست')),
                ('max_image_size', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='حداکثر حجم تصویر (مگابایت)')),
                ('email_host', models.CharField(blank=True, max_length=255, verbose_name='سرور ایمیل')),
                ('email_port', models.IntegerField(blank=True, default=587, verbose_name='پورت ایمیل')),
                ('email_username', models.CharField(blank=True, max_length=255, verbose_name='نام کاربری ایمیل')),
                ('email_password', models.CharField(blank=True, max_length=255, verbose_name='رمز ایمیل')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='استفاده از TLS')),
                ('email_from', models.CharField(blank=True, max_length=255, verbose_name='ایمیل فرستنده')),
                ('primary_color', models.CharField(default='#3498db', max_length=7, verbose_name='رنگ اصلی')),
                ('secondary_color', models.CharField(default='#2ecc71', max_length=7, verbose_name='رنگ ثانویه')),
                ('theme_mode', models.CharField(choices=[('light', 'روشن'), ('dark', 'تاریک'), ('auto', 'خودکار')], default='light', max_length=10, verbose_name='حالت ظاهری')),
                ('session_timeout', models.IntegerField(default=30, verbose_name='زمان انقضای جلسه (دقیقه)')),
                ('max_login_attempts', models.IntegerField(default=5, verbose_name='حداکثر تلاش برای ورود')),
                ('password_min_length', models.IntegerField(default=8, verbose_name='حداقل طول رمز عبور')),
                ('require_email_verification', models.BooleanField(default=False, verbose_name='نیاز به تایید ایمیل')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='حالت تعمیرات')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='پیام تعمیرات')),
                ('allow_registration', models.BooleanField(default=True, verbose_name='اجازه ثبت\u200cنام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات اپلیکیشن',
                'verbose_name_plural': 'تنظیمات اپلیکیشن',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('icon', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('item', 'Item'), ('tree', 'Tree')], default='item', max_length=10)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('icon', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('item', 'Item'), ('tree', 'Tree')], default='item', max_length=10)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('parent_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpages', to='dashboard.page')),
            ],
        ),
    ]
