# Generated by Django 6.0.7 on 2026-07-20 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='کد منحصر\u200cبه\u200cفرد انبار', max_length=20, unique=True, verbose_name='کد انبار')),
                ('name', models.CharField(help_text='نام نمایشی انبار', max_length=100, verbose_name='نام انبار')),
                ('number', models.PositiveIntegerField(default=1, help_text='یک عدد دلخواه برای انبار وارد کنید (مثبت)', verbose_name='شماره انبار')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبارها',
                'ordering': ['number', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_name', models.CharField(help_text='نامی که به این رابطه اختصاص می\u200cدهید', max_length=200, verbose_name='نام رابطه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_relations', to='SepidarApp.warehouse', verbose_name='انبار مقصد')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relations', to='SepidarApp.warehouse', verbose_name='انبار مبدا')),
            ],
            options={
                'verbose_name': 'رابطه انبار',
                'verbose_name_plural': 'روابط انبارها',
                'ordering': ['-created_at'],
                'unique_together': {('source_warehouse', 'destination_warehouse')},
            },
        ),
    ]
