# Generated by Django 6.1.1 on 2026-09-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SepidarApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouserelation',
            name='moin_code',
            field=models.IntegerField(blank=True, help_text='کد معین مرتبط با این رابطه', null=True, verbose_name='کد معین'),
        ),
        migrations.AddField(
            model_name='warehouserelation',
            name='order_registration_notes',
            field=models.TextField(blank=True, help_text='توضیحات یا نکات مربوط به ثبت سفارش برای این رابطه', null=True, verbose_name='توضیحات ثبت سفارش'),
        ),
    ]
