# Generated by Django 6.1.1 on 2026-09-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SepidarApp', '0002_warehouserelation_moin_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouserelation',
            name='cost_stock',
            field=models.IntegerField(blank=True, help_text='کد مرکز هزینه مرتبط با این رابطه', null=True, verbose_name='کد مرکز هزینه'),
        ),
    ]
