# Generated by Django 6.1.1 on 2026-09-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SepidarApp', '0003_warehouserelation_cost_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouserelation',
            name='deliverer_ref',
            field=models.IntegerField(blank=True, help_text='کد گیزنده با این رابطه', null=True, verbose_name='کد گیرنده'),
        ),
    ]
