# Generated by Django 6.0.5 on 2026-10-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SepidarApp', '0004_warehouserelation_deliverer_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_id', models.IntegerField(db_index=True, verbose_name='شناسه فرمول (سپیدار)')),
                ('formula_code', models.CharField(blank=True, max_length=50, verbose_name='کد فرمول')),
                ('formula_title', models.CharField(blank=True, max_length=255, verbose_name='عنوان فرمول')),
                ('formula_item_ref', models.IntegerField(blank=True, null=True, verbose_name='مرجع محصول')),
                ('formula_product_name', models.CharField(blank=True, max_length=255, verbose_name='نام محصول')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده از سپیدار')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('notes', models.TextField(blank=True, help_text='یادداشت مخصوص این رابطه-فرمول', null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_relations', to='SepidarApp.warehouserelation', verbose_name='رابطه انبار')),
            ],
            options={
                'verbose_name': 'فرمول رابطه',
                'verbose_name_plural': 'فرمول\u200cهای روابط',
                'ordering': ['formula_code'],
                'indexes': [models.Index(fields=['relation', 'formula_id'], name='SepidarApp__relatio_fca58c_idx'), models.Index(fields=['is_deleted'], name='SepidarApp__is_dele_782e09_idx')],
                'unique_together': {('relation', 'formula_id')},
            },
        ),
    ]
