# Generated by Django 6.0.5 on 2026-10-02 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SepidarApp', '0005_relationformula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_display_name', models.CharField(blank=True, help_text='نام کاربر در زمان ثبت (کش شده)', max_length=200, verbose_name='نام نمایشی کاربر')),
                ('action_type', models.CharField(choices=[('formula_submit', 'ثبت فرمول\u200cها'), ('formula_submit_failed', 'ثبت فرمول\u200cها (ناموفق)'), ('item_add_temp', 'افزودن ماده موقت')], default='formula_submit', max_length=50, verbose_name='نوع فعالیت')),
                ('relation_name', models.CharField(blank=True, max_length=200, verbose_name='نام رابطه (کش شده)')),
                ('receipt_number', models.CharField(blank=True, help_text='شماره رسید/سفارش تولیدی که ساخته شده', max_length=100, null=True, verbose_name='شماره رسید')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('details', models.JSONField(blank=True, help_text='اطلاعات کامل ثبت شده به صورت JSON', null=True, verbose_name='جزئیات')),
                ('total_formulas', models.IntegerField(default=0, verbose_name='تعداد فرمول\u200cها')),
                ('total_items', models.IntegerField(default=0, verbose_name='تعداد کل مواد')),
                ('total_temp_items', models.IntegerField(default=0, verbose_name='تعداد مواد موقت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ثبت')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='SepidarApp.warehouserelation', verbose_name='رابطه انبار')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاریخچه فعالیت',
                'verbose_name_plural': 'تاریخچه فعالیت\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='SepidarApp__user_id_35c614_idx'), models.Index(fields=['action_type', '-created_at'], name='SepidarApp__action__d696d7_idx')],
            },
        ),
    ]
