# Generated by Django 6.0.5 on 2026-07-02 10:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=50, verbose_name='شماره همراه')),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='رمز عبور')),
                ('is_active', models.BooleanField(default=True, verbose_name='آیا اکانت فعال است')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت نام')),
                ('avatar', models.ImageField(default='assets/profile_images/vipa_default.jpg', upload_to='assets/profile_images/')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('کاربر', 'User')], default='کاربر', max_length=10, verbose_name='نقش کاربر')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
            },
        ),
    ]
