# Generated by Django 6.0.5 on 2026-10-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sepidar_code',
            field=models.IntegerField(default=17, help_text='کد کاربر در نرم\u200cافزار سپیدار (پیش\u200cفرض: 17)', verbose_name='کد سپیدار'),
        ),
    ]
