# Generated by Django 6.0.5 on 2026-10-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_sepidar_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sepidar_username',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='نام کاربری سپیدار'),
        ),
    ]
