"""
Django settings for SekeSepidar project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zz*xe474r!n)+3c4y_yw-#(tf)2tl2t@fi!8w-tk3j58nge@ss'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['172.20.10.3','*']


# Application definition

INSTALLED_APPS = [
    'colorfield',  # اضافه کن
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'channels',
    'dashboard',
    'vipaThemeBuilder',
    'mainPage',
    'about',
    'licenseapp',
    'aboutapp',
    'SepidarApp',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'licenseapp.middleware.LicenseCheckMiddleware', 
]

ROOT_URLCONF = 'SekeSepidar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.menu_items_processor',  # ✅ add this line

            ],
        },
    },
]

WSGI_APPLICATION = 'SekeSepidar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/assets/'

STATICFILES_DIRS = [
    BASE_DIR / 'assets',
]


DEFAULT_PROFILE_PATH = '/assets/profile_images/vipa_default.jpg'

# settings.py
CSRF_COOKIE_HTTPONLY = False  # باید False باشد




# ✅ استفاده از Storage سفارشی
DEFAULT_FILE_STORAGE = 'SekeSepidar.custom_storages.UnlimitedFileSystemStorage'

# تنظیمات آپلود
FILE_UPLOAD_MAX_MEMORY_SIZE = 20000 * 1024 * 1024  # 50MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 20000 * 1024 * 1024  # 50MB
FILE_UPLOAD_PERMISSIONS = 0o644


# ✅ تنظیمات Media
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# ✅ اضافه کردن مسیرهای media
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
        # یا برای production از Redis استفاده کنید:
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'CONFIG': {
        #     "hosts": [('127.0.0.1', 6379)],
        # },
    },
}



# Where to redirect when @login_required is triggered (default: '/accounts/login/')
LOGIN_URL = '/authentication/sign-in'

# Where to redirect after successful login (default: '/accounts/profile/')
LOGIN_REDIRECT_URL = '/'

# Where to redirect after logout (default: None)
LOGOUT_REDIRECT_URL = '/authentication/sign-in'


LICENSE_FILE = 'license.key'
PUBLIC_KEY_FILE = 'public.pem'



# ============================================
# External SQL Server Database Settings
# ============================================

# روش اول: استفاده از Connection String کامل
SQL_SERVER_CONNECTION_STRING = (
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=WIN-1SSE4CQ9LKP\\AMINDB;"
    "DATABASE=AminDB1404_606876541;"
    "Trusted_Connection=yes;"
)

# روش دوم: استفاده از تنظیمات جداگانه (اختیاری)
SQL_USE_CONNECTION_STRING = False  # اگر True باشد از string بالا استفاده می‌کند
SQL_SERVER = 'DESKTOP-JKDSDCN\SEPIDAR'
SQL_DATABASE = 'Sepidar01'
SQL_DRIVER = '{ODBC Driver 17 for SQL Server}'
SQL_TRUSTED_CONNECTION = 'yes'

# اگر از Username/Password استفاده می‌کنید:
# SQL_USERNAME = 'your_username'
# SQL_PASSWORD = 'your_password'
# SQL_TRUSTED_CONNECTION = 'no'